quarkus:
  datasource:
    db-kind: mysql
    username: lowprofile
    password: lowprofile
    jdbc:
      url: jdbc:mysql://localhost:3306/lowprofile

  hibernate-orm:
    database:
      generation: update